# Generated by Django 5.2.7 on 2026-01-20 00:17

import cloudinary.models
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentQuantityPerProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_quantities",
                        to="components.component",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Quantity per Project",
                "verbose_name_plural": "Component Quantities per Project",
                "db_table": "component_quantity_per_project",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", tinymce.models.HTMLField()),
                (
                    "components",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        through="projects.ComponentQuantityPerProject",
                        to="components.component",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.AddField(
            model_name="componentquantityperproject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="component_quantities",
                to="projects.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="componentquantityperproject",
            unique_together={("project", "component")},
        ),
    ]
