# Generated by Django 5.2.10 on 2026-01-20 02:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="circuit_diagram",
            field=models.FileField(
                blank=True, null=True, upload_to="projects/circuits/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="electrical_github_repo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="manuals",
            field=models.FileField(
                blank=True, null=True, upload_to="projects/manuals/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mechanical_github_repo_folder",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="readme_electrical",
            field=models.FileField(
                blank=True, null=True, upload_to="projects/readmes/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="readme_mechanical",
            field=models.FileField(
                blank=True, null=True, upload_to="projects/readmes/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="readme_software",
            field=models.FileField(
                blank=True, null=True, upload_to="projects/readmes/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="software_github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="software_github_repo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("ONGOING", "Ongoing"),
                    ("FINAL", "Final"),
                ],
                default="UPCOMING",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="project",
            name="video_description_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="vision",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="which_hand",
            field=models.CharField(
                choices=[("LEFT", "Left"), ("RIGHT", "Right")],
                default="RIGHT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/images/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
