# Generated by Django 5.2.10 on 2026-01-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statusboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="The unique URL identifier for this component. Changing this after the profile is public will break existing links.",
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="default/"),
                ),
                ("heading", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("ONGOING", "Ongoing"),
                            ("TESTING", "Testing"),
                            ("REVIEW", "Review"),
                            ("ACCEPTED", "Accepted"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="statusboards", to="projects.project"
                    ),
                ),
            ],
            options={
                "db_table": "statusboards",
            },
        ),
    ]
