# Generated by Django 5.2.10 on 2026-01-22 06:58

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_statusboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentquantityperproject",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="componentquantityperproject",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("UK", "United Kingdom"),
                            ("NP", "Nepal"),
                            ("DE", "Germany"),
                            ("IN", "India"),
                        ],
                        default="US",
                        max_length=2,
                    ),
                ),
                ("story_content", tinymce.models.HTMLField()),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="project_stories", to="projects.project"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stories",
                "db_table": "stories",
            },
        ),
    ]
