# Generated by Django 5.2.10 on 2026-01-22 07:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_componentquantityperproject_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(max_length=50)),
                ("description", tinymce.models.HTMLField()),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="use_cases", to="projects.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Use Case",
                "verbose_name_plural": "Use Cases",
                "db_table": "use_cases",
            },
        ),
    ]
