# Generated by Django 5.2.10 on 2026-01-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statusboard",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="story",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="usecase",
            name="projects",
        ),
        migrations.AddField(
            model_name="statusboard",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statusboard",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="usecase",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usecases",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="projects.project",
            ),
        ),
    ]
