# Generated by Django 5.2.10 on 2026-01-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_projectimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="projects/stages/gallery/")),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_images",
                        to="projects.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage Image",
                "verbose_name_plural": "Stage Gallery",
                "db_table": "stage_images",
            },
        ),
    ]
