services:
  frontend:
    build:
      context: ./../frontend
      dockerfile: Dockerfile.production
    container_name: compass-frontend-prod
    command: serve -s dist -l tcp://0.0.0.0:5173
    ports:
      - "5173:5173"
    networks:
      - compassNetworkProd

  db:
    image: mysql:latest
    container_name: compass-db-prod
    volumes:
      - compass-data:/var/lin/mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=compassDB
    networks:
      - compassNetworkProd

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./../backend
      dockerfile: Dockerfile.production
    environment:
      DJANGO_ENV: "${DJANGO_ENV}"
    container_name: compass-backend-prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - compassNetworkProd

volumes:
  compass-data:

networks:
  compassNetworkProd:
    driver: bridge
