# Generated by Django 5.2.10 on 2026-01-20 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_circuit_diagram_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("quote", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="contributors/images/"
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_accepted", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=25)),
                (
                    "contributor_type",
                    models.CharField(
                        choices=[
                            ("ELECTRIC", "Electric"),
                            ("MECHANIC", "Mechanic"),
                            ("SOFTWARE", "Software"),
                            ("OTHERS", "Others"),
                        ],
                        default="OTHERS",
                        max_length=20,
                    ),
                ),
                (
                    "file_mechanical",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contributors/files/mechanical/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["step", "stp"]
                            )
                        ],
                    ),
                ),
                (
                    "file_electrical",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contributors/files/electrical/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["sch"]
                            )
                        ],
                    ),
                ),
                (
                    "file_software",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contributors/files/software/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["py", "zip"]
                            )
                        ],
                    ),
                ),
                (
                    "file_others",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contributors/files/others/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["doc", "docx", "pdf"]
                            )
                        ],
                    ),
                ),
                ("projects", models.ManyToManyField(blank=True, to="projects.project")),
            ],
            options={
                "db_table": "contributors",
            },
        ),
    ]
