# Generated by Django 5.2.10 on 2026-01-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="slug",
            field=models.SlugField(
                help_text="The unique URL identifier for this component. Changing this after the profile is public will break existing links.",
                unique=True,
            ),
        ),
    ]
