services:
  frontend:
    build:
      context: ./../frontend
      dockerfile: Dockerfile.production
    container_name: prosthetic-frontend-prod
    command: serve -s dist -l tcp://0.0.0.0:5173
    ports:
      - "5173:5173"
    networks:
      - prostheticNetworkProd

  db:
    image: mysql:latest
    container_name: prosthetic-db-prod
    volumes:
      - prosthetic-data:/var/lin/mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prostheticDB
    networks:
      - prostheticNetworkProd

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./../backend
      dockerfile: Dockerfile.production
    environment:
      DJANGO_ENV: "${DJANGO_ENV}"
    container_name: prosthetic-backend-prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - prostheticNetworkProd

volumes:
  prosthetic-data:

networks:
  prostheticNetworkProd:
    driver: bridge
