# Generated by Django 5.2.7 on 2026-01-20 00:17

import cloudinary.models
import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Mechanical", "Mechanical"),
                            ("Electrical", "Electrical"),
                            ("Software", "Software"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", tinymce.models.HTMLField()),
                ("specs", tinymce.models.HTMLField()),
                (
                    "cad_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload CAD files (STL, STEP, IGES, DWG, DXF)",
                        null=True,
                        upload_to="cad_files/components/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "stl",
                                    "step",
                                    "stp",
                                    "iges",
                                    "igs",
                                    "dwg",
                                    "dxf",
                                ]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "components",
            },
        ),
    ]
