# Generated by Django 5.2.10 on 2026-01-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="part_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="component",
            name="resource_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="component",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="components/images/"
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="component",
            name="type",
            field=models.CharField(
                choices=[("MECHANICAL", "Mechanical"), ("ELECTRICAL", "Electrical")],
                default="MECHANICAL",
                max_length=20,
            ),
        ),
    ]
