# Generated by Django 5.2.10 on 2026-01-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_component_part_no_component_resource_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="slug",
            field=models.SlugField(
                help_text="The unique URL identifier for this component. Changing this after the profile is public will break existing links.",
                unique=True,
            ),
        ),
    ]
