services:
  frontend:
    build:
      context: ./../frontend
      dockerfile: Dockerfile.dev
    container_name: prosthetic-frontend-dev
    ports:
      - "5174:5174"
    volumes:
      - ./../frontend:/frontend
      - /frontend/node_modules


  db:
    image: mysql:latest
    container_name: prosthetic-db
    volumes:
      - prosthetic-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prostheticDB
    networks:
      - prostheticNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./../backend
      dockerfile: Dockerfile.dev
    container_name: prosthetic-backend-dev
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate && 
              python manage.py create_default_superuser &&
              python manage.py runserver 0.0.0.0:8081"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ./../backend:/backend
      - /app/.venv
    networks:
      - prostheticNetwork
volumes:
  prosthetic-data:
networks:
  prostheticNetwork:
    driver: bridge
